### PR TITLE
feat: refactoring to allow dataset file to be translated independently

### PR DESCRIPTION
**Pull request by narukaioh**
I am refactoring this line of code so that we can independently translate the dataset file.

### CODE REVIEW

**Comment by narukaioh** [comment]
I keep working on this one, I just need to map the skills the right way

**Comment by narukaioh** [comment]
I would like to thank you @danielmacapa for making the translation into Portuguese. He doesn't know about github to do a PR, so I leave my thanks here!

**Comment by aMediocreDad** [comment]
> 
> 
> I would like to thank you @danielmacapa for making the translation into Portuguese. He doesn't know about github to do a PR, so I leave my thanks here!

**Comment by aMediocreDad** [comment]
> I keep working on this one, I just need to map the skills the right way

Super! I will merge this one now, so open a new with the rest of the changes later.

The rewrite is overdue by a day, and I want to get it done while it's somewhat quiet.

**Pull request merged**
