### PR TITLE
Additional encumbrance

### PR DESCRIPTION
**Pull request by roonel**
Added the option to change the maximum encumbrance of characters on the sheet (supporting the Pack Rat talent)

### CODE REVIEW

**Comment by jimorie** [comment]
Two thoughts from a regular user (so feel free to ignore):

a) Shouldn't `extraEncumbrance` also be added to the data model in `template.json`?

b) An alternative to this solution could be to implement bonuses to carrying capacity as a roll modifier instead, that can be added to your Pack Rat talent. My feeling is that it would perhaps be a bit cleaner (although less obvious for the user).

**Comment by roonel** [comment]
Thanks for the tips! This is my first dabbling in foundry related coding, so some conventions I'm not familiar with.
> a) Shouldn't `extraEncumbrance` also be added to the data model in `template.json`?

I'll definitely look into this one!

> b) An alternative to this solution could be to implement bonuses to carrying capacity as a roll modifier instead, that can be added to your Pack Rat talent. My feeling is that it would perhaps be a bit cleaner (although less obvious for the user).

Originally made this function before the roll modifier was added to the system. But I agree that it would be cleaner, but I'm not sure how well it would fit into that category.

**Comment by jimorie** [comment]
> Originally made this function before the roll modifier was added to the system. I agree that it would be cleaner, but I'm not sure how well it would fit into that category.

Yep, I see. I think it could make sense to have an "Other" category of misc modifiers where it could fit. But you should do your thing here -- I don't want to steal your thunder. Just ping me if you'd like a PR with the alternative roll modifier solution and I can easily do that.

**Comment by roonel** [comment]
I fixed the template.json and created a separate PR with the roll modifier version. Thanks for the help and Swedish translation!

**Review by aMediocreDad — COMMENTED** [review]
This will be closed as #6 adds the same feature.

**Pull request closed without merging**
