### PR TITLE
Taiwanese Localization

### PR DESCRIPTION
**Pull request by Rosataker**

### CODE REVIEW

**Comment by aMediocreDad** [comment]
Hello! Thanks for adding Taiwanese localization 😁 Please fix the filename as advised in comment.

**Review by aMediocreDad — CHANGES_REQUESTED** [review]
The file name should be `.json` not `.js` 😉

**Comment by Rosataker** [comment]
hello, i changed fille name. thanks you! and...

it's for system.json

    {
      "lang": "zh_TW",
      "name": "正體中文",
      "path": "lang/zh_TW.json"
    }

**Review by aMediocreDad — APPROVED** [review]

**Comment by aMediocreDad** [comment]
I have renamed and added to system.json as well as confirmed functionality. 

Thank you for the effort! I see we need to work on changes to the font sizing in the sheets as they are currently too small with CJK character sets.

**Pull request merged**
