### PR TITLE
Character Generator as is

### PR DESCRIPTION
**Pull request by maxstar**
I was calling it with a macro: 
`Hooks.call('generateCharacterForm', [{}]);`

### CODE REVIEW

**Comment by aMediocreDad** [comment]
> I was calling it with a macro: 
> 
> `Hooks.call('generateCharacterForm', [{}]);`

Great! I am thinking we could replace the push buttons (now that I am refactoring the dice roller) with a config button that lets you open the character generator.

**Comment by maxstar** [comment]
> Great! I am thinking we could replace the push buttons (now that I am refactoring the dice roller) with a config button that lets you open the character generator.

That's possible, although logic will have to be modified to update the existing entity instead of creating a new one. And there has to be some sort of "fool protection" to not overwrite already created and functioning character.

**Comment by aMediocreDad** [comment]
Shouldn't be a problem:)

Looked through it and see the points that need to be changed.

**Review by aMediocreDad — APPROVED** [review]
I have gone ahead and merged all the files with the system and updated as needed.

Only thing missing the feature that updates the actor instead of creating one. And some layout issues.

**Pull request merged**
